entrance:
    path:     /entrance/
    defaults: { _controller: OTBackendBundle:Security:entrance }

admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: OTBackendBundle:Admin:dashboard }

admin_teacher:
    path:     /admin/teacher
    defaults: { _controller: OTBackendBundle:Admin:teacher }

admin_learner:
    path:     /admin/learner
    defaults: { _controller: OTBackendBundle:Admin:learner }

admin_course:
    path:     /admin/course
    defaults: { _controller: OTBackendBundle:Admin:course }

admin_account:
    path:     /admin/account
    defaults: { _controller: OTBackendBundle:Admin:account }

admin_setting:
    path:     /admin/setting
    defaults: { _controller: OTBackendBundle:Admin:setting }
