entrance:
    path:     /entrance/
    defaults: { _controller: OTBackendBundle:Security:entrance }

admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: OTBackendBundle:Admin:dashboard }

admin_teacher:
    path:     /admin/teacher
    defaults: { _controller: OTBackendBundle:Admin:teacher }

admin_learner:
    path:     /admin/learner
    defaults: { _controller: OTBackendBundle:Admin:learner }

admin_course_list_all:
    path:     /admin/course/list/all
    defaults: { _controller: OTBackendBundle:Course:adminCourseListAll }

admin_course_list_pending:
    path:     /admin/course/list/pending
    defaults: { _controller: OTBackendBundle:Course:adminCourseListPending }

admin_course_list_record:
    path:     /admin/course/list/record
    defaults: { _controller: OTBackendBundle:Course:adminCourseListRecord }

admin_account:
    path:     /admin/account
    defaults: { _controller: OTBackendBundle:Admin:account }

admin_setting:
    path:     /admin/setting
    defaults: { _controller: OTBackendBundle:Admin:setting }
