entrance:
    path:     /entrance/
    defaults: { _controller: OTBackendBundle:Security:entrance }

OTBackendBundle_admin_user:
        resource: "@OTBackendBundle/Resources/config/routing/admin_user.yml"
        prefix:   /admin/user

OTBackendBundle_admin_course:
        resource: "@OTBackendBundle/Resources/config/routing/admin_course.yml"
        prefix:   /admin/course

admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: OTBackendBundle:Admin:dashboard }

admin_account_overview:
    path:     /admin/account/overview
    defaults: { _controller: OTBackendBundle:User:adminAccountOverview }

admin_account_transactionrecord_list:
    path:     /admin/account/transactionrecord/list
    defaults: { _controller: OTBackendBundle:TransactionRecord:adminAccountTranscationRecordList }

admin_account_transfer:
    path:     /admin/account/transfer
    defaults: { _controller: OTBackendBundle:TransactionRecord:adminAccountTransfer }

admin_setting:
    path:     /admin/setting
    defaults: { _controller: OTBackendBundle:Admin:setting }

user_profile_change_password:
    path:     /user/profile/changepassword
    defaults: { _controller: OTBackendBundle:User:profileChangePassword }
