entrance:
    path:     /entrance/
    defaults: { _controller: OTBackendBundle:Security:entrance }

admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: OTBackendBundle:Admin:dashboard }

admin_teacher_list:
    path:     /admin/teacher/list
    defaults: { _controller: OTBackendBundle:User:adminTeacherList }

admin_learner_list:
    path:     /admin/learner/list
    defaults: { _controller: OTBackendBundle:User:adminLearnerList }

admin_course_list_all:
    path:     /admin/course/listall
    defaults: { _controller: OTBackendBundle:Course:adminCourseListAll }

admin_course_list_pending:
    path:     /admin/course/list/pending
    defaults: { _controller: OTBackendBundle:Course:adminCourseListPending }

admin_course_list_record:
    path:     /admin/course/list/record
    defaults: { _controller: OTBackendBundle:Course:adminCourseListRecord }

admin_course_change_status:
    path:     /admin/course/list/changestatus/{courseid}/{status}/{redirect}
    defaults: { _controller: OTBackendBundle:Course:adminCourseChangeStatus }

admin_account_overview:
    path:     /admin/account/overview
    defaults: { _controller: OTBackendBundle:User:adminAccountOverview }

admin_account_transactionrecord_list:
    path:     /admin/account/transactionrecord/list
    defaults: { _controller: OTBackendBundle:TransactionRecord:adminAccountTranscationRecordList }

admin_account_transfer:
    path:     /admin/account/transfer
    defaults: { _controller: OTBackendBundle:TransactionRecord:adminAccountTransfer }

admin_setting:
    path:     /admin/setting
    defaults: { _controller: OTBackendBundle:Admin:setting }

user_change_current_password:
    path:     /user/changecurrentpassword/
    defaults: { _controller: OTBackendBundle:User:changeCurrentPassword }

admin_force_change_password:
    path:     /admin/forcechangepassword/
    defaults: { _controller: OTBackendBundle:User:forcechangePassword }
