entrance:
    path:     /entrance/
    defaults: { _controller: OTBackendBundle:Security:entrance }
dashboard:
    path:     /dashboard
    defaults: { _controller: OTBackendBundle:Admin:dashboard }

teacher:
    path:     /teacher
    defaults: { _controller: OTBackendBundle:Admin:teacher }

learner:
    path:     /learner
    defaults: { _controller: OTBackendBundle:Admin:learner }

course:
    path:     /course
    defaults: { _controller: OTBackendBundle:Admin:course }

account:
    path:     /account
    defaults: { _controller: OTBackendBundle:Admin:account }

setting:
    path:     /setting
    defaults: { _controller: OTBackendBundle:Admin:setting }
