default:
    path:     /
    defaults: { _controller: OTBackendBundle:Homepage:index }

homepage:
    path:     /homepage
    defaults: {_controller: OTBackendBundle:Homepage:index}

login:
    path:     /login
    defaults: { _controller: OTBackendBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

entrance:
    path: /entrance
    defaults: {_controller: OTBackendBundle:Security:entrance }

ot_backend:
    resource: "@OTBackendBundle/Resources/config/routing.yml"
    prefix:   /backend


