security:
    encoders:
        OT\BackendBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]
        ROLE_TEACHER:     [ TEACHER ]
        ROLE_LEARNER:     [ LEARNER ]

    providers:
        users:
            entity: { class: OTBackendBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /entrance
            logout:
                path: /logout
                target: /
