security:
    encoders:
        OT\BackendBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ ADMIN, ROLE_TEACHER, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        users:
            entity: { class: OTBackendBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /entrance
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ~/entrance, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/admin/, roles: ROLE_ADMIN }
        - { path: ^/backend/teacher/, roles: ROLE_TEACHER }
        - { path: ^/backend/learner/, roles: ROLE_LEARNER }

            # Include the following line to also secure the /admin path itself
            # - { path: ^/backend/admin$, roles: ROLE_ADMIN }
