admin_user:
    path:     /
    defaults: { _controller: "OTBackendBundle:User:index" }

admin_user_new:
    path:     /new
    defaults: { _controller: "OTBackendBundle:User:new" }

admin_user_create:
    path:     /create
    defaults: { _controller: "OTBackendBundle:User:create" }
    requirements: { _method: post }

admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "OTBackendBundle:User:edit" }

admin_user_list:
    path:     /list
    defaults: { _controller: "OTBackendBundle:User:list" }

admin_user_update:
    path:     /{id}/update
    defaults: { _controller: "OTBackendBundle:User:update" }
    requirements: { _method: post|put }

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "OTBackendBundle:User:delete" }
    requirements: { _method: post|delete }

admin_user_change_password:
    path:     /changepassword
    defaults: { _controller: OTBackendBundle:User:adminChangePassword }
