teacher_dashboard:
    path:     /dashboard
    defaults: { _controller: "OTBackendBundle:Teacher:dashboard" }

teacher_account_transactionrecord_list:
    path:     /account/transactionrecord/list/
    defaults: { _controller: "OTBackendBundle:TransactionRecord:accountTransactionRecordList" }

