teacher_dashboard:
    path:     /dashboard
    defaults: { _controller: "OTBackendBundle:Teacher:dashboard" }

teacher_course_history_list:
    path:     /teacher_course_history/list
    defaults: { _controller: "OTBackendBundle:BookedTime:courseHistoryList" }
