<?php

namespace OT\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
	
	public function getPendingNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(c)')
			->from('OTBackendBundle:Course','c')
			->where('c.status = :status')
			->setParameter('status','PENDING')
			->getQuery()->getSingleResult()[1];
	}
}
