<?php

namespace OT\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearnerRepository extends EntityRepository
{
	public function getLearnerBalanceSum()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('SUM(l.account_balance)')
			->from('OTBackendBundle:Learner','l')
			->getQuery()->getSingleResult();
	}

	public function getLearnerNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(l)')
			->from('OTBackendBundle:Learner','l')
			->getQuery()->getSingleResult();
	}
	public function getLearnerList()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('l')
			->from('OTBackendBundle:Learner','l')
			->getQuery()->getResult();
	}

}
