<?php

namespace OT\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getUserBalanceSum()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('SUM(t.account_balance)')
			->from('OTBackendBundle:User','t')
			->where('t.roles = :roles1 OR t.roles = :roles2')
			->setParameter('roles1','ADMIN')
			->setParameter('roles2','User')
			->getQuery()->getSingleResult();
	}

	public function getUserNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(t)')
			->from('OTBackendBundle:User','t')
			->where('t.roles = :roles1 OR t.roles = :roles2')
			->setParameter('roles1','User')
			->setParameter('roles2','ADMIN')
			->getQuery()->getSingleResult();
	}

	public function getAdminNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(a)')
			->from('OTBackendBundle:User','a')
			->where('a.roles = :roles')
			->setParameter('roles','ADMIN')
			->getQuery()->getSingleResult();
	}

	public function getUserList()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('t')
			->from('OTBackendBundle:User','t')
			->where('t.roles = :roles1 OR t.roles = :roles2')
			->setParameter('roles1','User')
			->setParameter('roles2','ADMIN')
			->getQuery()->getResult();
	}
}
