<?php

namespace OT\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getTeacherBalanceSum()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('SUM(t.account_balance)')
			->from('OTBackendBundle:User','t')
			->where('t.role = :role1 OR t.role = :role2')
			->setParameter('role1','ADMIN')
			->setParameter('role2','TEACHER')
			->getQuery()->getSingleResult();
	}

	public function getLearnerBalanceSum()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('SUM(t.account_balance)')
			->from('OTBackendBundle:User','t')
			->where('t.role = :role1')
			->setParameter('role1','LEARNER')
			->getQuery()->getSingleResult();
	}


	public function getTeacherNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(t)')
			->from('OTBackendBundle:User','t')
			->where('t.role = :role1 OR t.role = :role2')
			->setParameter('role1','ADMIN')
			->setParameter('role2','TEACHER')
			->getQuery()->getSingleResult();
	}

	public function getLearnerNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(t)')
			->from('OTBackendBundle:User','t')
			->where('t.role = :role1')
			->setParameter('role1','LEARNER')
			->getQuery()->getSingleResult();
	}

	public function getAdminNumber()
	{
		return $this->getEntityManager()->createQueryBuilder()
			->select('COUNT(a)')
			->from('OTBackendBundle:User','a')
			->where('a.role = :role')
			->setParameter('role','ADMIN')
			->getQuery()->getSingleResult();
	}
}
